//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitySplittingDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContactDetails
    {
        public int Id { get; set; }
        public string MobileNo { get; set; }
        public string Location { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
